# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logagent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logagent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elogagent.proto\x12\x08logagent\"C\n\nLogRequest\x12\x11\n\tjson_data\x18\x01 \x01(\t\x12\x11\n\tpipelines\x18\x02 \x03(\t\x12\x0f\n\x07\x61pi_key\x18\x03 \x01(\t\"/\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2B\n\x08LogAgent\x12\x36\n\x07SendLog\x12\x14.logagent.LogRequest\x1a\x15.logagent.LogResponseB*Z(github.com/datanadhi/echopost/logagentpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logagent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/datanadhi/echopost/logagentpb'
  _globals['_LOGREQUEST']._serialized_start=28
  _globals['_LOGREQUEST']._serialized_end=95
  _globals['_LOGRESPONSE']._serialized_start=97
  _globals['_LOGRESPONSE']._serialized_end=144
  _globals['_LOGAGENT']._serialized_start=146
  _globals['_LOGAGENT']._serialized_end=212
# @@protoc_insertion_point(module_scope)
